"""init_all_models

Revision ID: c62461a9f6dc
Revises: 
Create Date: 2026-02-13 02:07:12.552169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c62461a9f6dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.add_column('care_activities', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('care_activities', 'staff_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('care_activities', 'staff_role',
               existing_type=postgresql.ENUM('nurse', 'surgeon', 'specialist', name='stafftype'),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('care_activities', 'activity_type',
               existing_type=postgresql.ENUM('vital_signs', 'medication_administration', 'wound_care', 'patient_hygiene', 'mobilization', 'observation', 'procedure_prep', 'post_op_care', 'patient_education', 'other', name='activitytype'),
               nullable=True)
    op.alter_column('care_activities', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('care_activities', 'is_pre_operative',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="CASE WHEN lower(coalesce(is_pre_operative, '')) IN ('true','t','1','yes','y') THEN true ELSE false END")
    op.alter_column('care_activities', 'is_post_operative',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="CASE WHEN lower(coalesce(is_post_operative, '')) IN ('true','t','1','yes','y') THEN true ELSE false END")
    op.alter_column('care_activities', 'procedure_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('care_activities', 'intervention_required',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="CASE WHEN lower(coalesce(intervention_required, '')) IN ('true','t','1','yes','y') THEN true ELSE false END")
    op.alter_column('care_activities', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'cancelled', name='activitystatus'),
               nullable=True)
    op.drop_index(op.f('ix_care_activities_activity_type'), table_name='care_activities')
    op.drop_index(op.f('ix_care_activities_staff_role'), table_name='care_activities')
    op.drop_index(op.f('ix_care_activities_status'), table_name='care_activities')
    op.drop_index(op.f('ix_care_activities_care_activity_id'), table_name='care_activities')
    op.create_index(op.f('ix_care_activities_care_activity_id'), 'care_activities', ['care_activity_id'], unique=True)
    op.create_index(op.f('ix_care_activities_id'), 'care_activities', ['id'], unique=False)
    op.drop_constraint(op.f('care_activities_assignment_id_fkey'), 'care_activities', type_='foreignkey')
    op.drop_constraint(op.f('care_activities_patient_id_fkey'), 'care_activities', type_='foreignkey')
    op.drop_column('care_activities', 'staff_specialty')
    op.drop_column('care_activities', 'post_op_complications')
    op.drop_column('care_activities', 'follow_up_required')
    op.drop_column('care_activities', 'care_plan_notes')
    op.drop_column('care_activities', 'complications_noted')
    op.drop_column('care_activities', 'follow_up_schedule')
    op.drop_column('care_activities', 'completed_at')
    op.drop_column('care_activities', 'pre_op_checklist_items')
    op.add_column('drugs', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('drugs', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('drugs', 'generic_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('drugs', 'brand',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('drugs', 'strength',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('drugs', 'formulation',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('drugs', 'unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('drugs', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('drugs', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('drugs', 'supplier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('drugs', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.drop_index(op.f('ix_drugs_drug_id'), table_name='drugs')
    op.create_index(op.f('ix_drugs_drug_id'), 'drugs', ['drug_id'], unique=True)
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.add_column('patients', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_column('patients', 'email')
    op.drop_column('patients', 'triage_status')
    op.drop_column('patients', 'triage_date')
    op.drop_column('patients', 'temperature')
    op.drop_column('patients', 'pulse')
    op.drop_column('patients', 'respiratory_rate')
    op.drop_column('patients', 'blood_type')
    op.drop_column('patients', 'blood_pressure_diastolic')
    op.drop_column('patients', 'complaints')
    op.drop_column('patients', 'triage_notes')
    op.drop_column('patients', 'blood_pressure_systolic')
    op.add_column('supplies', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('supplies', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('supplies', 'unit',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('supplies', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('supplies', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('supplies', 'supplier',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('supplies', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.create_index(op.f('ix_supplies_name'), 'supplies', ['name'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_supplies_name'), table_name='supplies')
    op.alter_column('supplies', 'location',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('supplies', 'supplier',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('supplies', 'expiration_date',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('supplies', 'batch_number',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('supplies', 'unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('supplies', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('supplies', 'description')
    op.add_column('patients', sa.Column('blood_pressure_systolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('triage_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('complaints', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('blood_pressure_diastolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('blood_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('respiratory_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('pulse', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('triage_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('triage_status', postgresql.ENUM('EMERGENCY', 'URGENT', 'SEMI_URGENT', 'NON_URGENT', 'COMPLETED', name='triagestatus'), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.alter_column('patients', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               existing_nullable=True)
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('patients', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('patients', 'notes')
    op.drop_column('patients', 'address')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_drug_id'), table_name='drugs')
    op.create_index(op.f('ix_drugs_drug_id'), 'drugs', ['drug_id'], unique=False)
    op.alter_column('drugs', 'location',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('drugs', 'supplier',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('drugs', 'expiration_date',
               existing_type=sa.String(length=50),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('drugs', 'batch_number',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drugs', 'unit',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('drugs', 'formulation',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drugs', 'strength',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('drugs', 'brand',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('drugs', 'generic_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('drugs', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('drugs', 'id')
    op.add_column('care_activities', sa.Column('pre_op_checklist_items', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('follow_up_schedule', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('complications_noted', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('care_plan_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('follow_up_required', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('post_op_complications', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('care_activities', sa.Column('staff_specialty', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('care_activities_patient_id_fkey'), 'care_activities', 'patients', ['patient_id'], ['patient_id'])
    op.create_foreign_key(op.f('care_activities_assignment_id_fkey'), 'care_activities', 'assignments', ['assignment_id'], ['assignment_id'])
    op.drop_index(op.f('ix_care_activities_id'), table_name='care_activities')
    op.drop_index(op.f('ix_care_activities_care_activity_id'), table_name='care_activities')
    op.create_index(op.f('ix_care_activities_care_activity_id'), 'care_activities', ['care_activity_id'], unique=False)
    op.create_index(op.f('ix_care_activities_status'), 'care_activities', ['status'], unique=False)
    op.create_index(op.f('ix_care_activities_staff_role'), 'care_activities', ['staff_role'], unique=False)
    op.create_index(op.f('ix_care_activities_activity_type'), 'care_activities', ['activity_type'], unique=False)
    op.alter_column('care_activities', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'completed', 'cancelled', name='activitystatus'),
               nullable=False)
    op.alter_column('care_activities', 'intervention_required',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('care_activities', 'procedure_type',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('care_activities', 'is_post_operative',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('care_activities', 'is_pre_operative',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('care_activities', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('care_activities', 'activity_type',
               existing_type=postgresql.ENUM('vital_signs', 'medication_administration', 'wound_care', 'patient_hygiene', 'mobilization', 'observation', 'procedure_prep', 'post_op_care', 'patient_education', 'other', name='activitytype'),
               nullable=False)
    op.alter_column('care_activities', 'staff_role',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('nurse', 'surgeon', 'specialist', name='stafftype'),
               nullable=False)
    op.alter_column('care_activities', 'staff_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('care_activities', 'id')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # ### end Alembic commands ###
